# Generated by Django 3.0.5 on 2020-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200506_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Toppings'),
        ),
    ]
